import typing


class ProxyStore(typing.Protocol):
    def store(self, uuid, country_city, proxy_connection, browser_profile, tags = [], ip = None): ...
    def query_country_city(self,value): ...
    def query_tag(self,value): ...
    def validate(self): ...